"""wp6_job_ext_key

Revision ID: 2bba465be0ad
Revises: 88ae66606d3b
Create Date: 2026-09-16 09:12:24.351300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bba465be0ad'
down_revision: Union[str, Sequence[str], None] = '88ae66606d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ext_job_key', sa.String(length=128), nullable=True))
    op.create_index('uq_jobs_ext_key', 'jobs', ['ext_id', 'ext_job_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_jobs_ext_key', table_name='jobs')
    op.drop_column('jobs', 'ext_job_key')
    # ### end Alembic commands ###
