"""wp12 host_tag managed_by_ext_id

Revision ID: 53b6fedfa84e
Revises: 2bba465be0ad
Create Date: 2026-09-17 00:14:06.093660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b6fedfa84e'
down_revision: Union[str, Sequence[str], None] = '2bba465be0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_tags', sa.Column('managed_by_ext_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_tags', 'managed_by_ext_id')
    # ### end Alembic commands ###
