"""initial schema

Revision ID: 5637ec0a6a73
Revises: 
Create Date: 2026-09-14 22:28:29.334865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5637ec0a6a73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_flap_history',
    sa.Column('host_id', sa.String(length=36), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_flap_history'))
    )
    op.create_index(op.f('ix_action_flap_history_fingerprint'), 'action_flap_history', ['fingerprint'], unique=False)
    op.create_index('ix_flap_fingerprint_ts', 'action_flap_history', ['fingerprint', 'ts'], unique=False)
    op.create_table('audit_log',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_correlation', 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_index('ix_audit_ts_action', 'audit_log', ['ts', 'action'], unique=False)
    op.create_table('connector_instances',
    sa.Column('ext_id', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('health_message', sa.String(length=255), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_instances'))
    )
    op.create_index(op.f('ix_connector_instances_ext_id'), 'connector_instances', ['ext_id'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_layouts'))
    )
    op.create_index(op.f('ix_dashboard_layouts_user_id'), 'dashboard_layouts', ['user_id'], unique=False)
    op.create_table('extensions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('api_version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('granted_permissions', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extensions'))
    )
    op.create_table('host_groups',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_host_groups_name'))
    )
    op.create_table('hosts',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('os_family', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('provider_ext_id', sa.String(length=64), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosts')),
    sa.UniqueConstraint('provider_ext_id', 'provider_ref', name='provider_ref')
    )
    op.create_index(op.f('ix_hosts_name'), 'hosts', ['name'], unique=True)
    op.create_index(op.f('ix_hosts_provider_ext_id'), 'hosts', ['provider_ext_id'], unique=False)
    op.create_table('jobs',
    sa.Column('ext_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_ext_id'), 'jobs', ['ext_id'], unique=False)
    op.create_table('notifications',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_ext_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_ts'), 'notifications', ['ts'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('secrets',
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('owner_ext_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets'))
    )
    op.create_index(op.f('ix_secrets_label'), 'secrets', ['label'], unique=True)
    op.create_index(op.f('ix_secrets_owner_ext_id'), 'secrets', ['owner_ext_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('key', 'scope', 'user_id', name=op.f('pk_settings'))
    )
    op.create_table('actions',
    sa.Column('ext_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('proposed_by_type', sa.String(length=16), nullable=False),
    sa.Column('proposed_by_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('gate_decision', sa.JSON(), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_actions_host_id_hosts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index('ix_actions_correlation', 'actions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_actions_ext_id'), 'actions', ['ext_id'], unique=False)
    op.create_index(op.f('ix_actions_idempotency_key'), 'actions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_index('ix_actions_status_created', 'actions', ['status', 'created_at'], unique=False)
    op.create_table('host_credentials',
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('secret_id', sa.String(length=36), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_host_credentials_host_id_hosts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], name=op.f('fk_host_credentials_secret_id_secrets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_credentials'))
    )
    op.create_index(op.f('ix_host_credentials_host_id'), 'host_credentials', ['host_id'], unique=False)
    op.create_table('host_group_members',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['host_groups.id'], name=op.f('fk_host_group_members_group_id_host_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_host_group_members_host_id_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'host_id', name=op.f('pk_host_group_members'))
    )
    op.create_table('host_tags',
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_host_tags_host_id_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('host_id', 'tag', name=op.f('pk_host_tags'))
    )
    op.create_index(op.f('ix_host_tags_tag'), 'host_tags', ['tag'], unique=False)
    op.create_table('job_runs',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('ext_id', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output_ref', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('actor', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index(op.f('ix_job_runs_ext_id'), 'job_runs', ['ext_id'], unique=False)
    op.create_index(op.f('ix_job_runs_started_at'), 'job_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_index('ix_runs_job_started', 'job_runs', ['job_id', 'started_at'], unique=False)
    op.create_table('known_hosts',
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('key_type', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_known_hosts_host_id_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_known_hosts'))
    )
    op.create_index(op.f('ix_known_hosts_host_id'), 'known_hosts', ['host_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission', name=op.f('pk_role_permissions'))
    )
    op.create_table('secret_grants',
    sa.Column('secret_id', sa.String(length=36), nullable=False),
    sa.Column('grantee_type', sa.String(length=16), nullable=False),
    sa.Column('grantee_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], name=op.f('fk_secret_grants_secret_id_secrets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('secret_id', 'grantee_type', 'grantee_id', name=op.f('pk_secret_grants'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['totp_secret_id'], ['secrets.id'], name=op.f('fk_users_totp_secret_id_secrets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens'))
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('secret_grants')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_known_hosts_host_id'), table_name='known_hosts')
    op.drop_table('known_hosts')
    op.drop_index('ix_runs_job_started', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_started_at'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_ext_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_host_tags_tag'), table_name='host_tags')
    op.drop_table('host_tags')
    op.drop_table('host_group_members')
    op.drop_index(op.f('ix_host_credentials_host_id'), table_name='host_credentials')
    op.drop_table('host_credentials')
    op.drop_index('ix_actions_status_created', table_name='actions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_idempotency_key'), table_name='actions')
    op.drop_index(op.f('ix_actions_ext_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_index('ix_actions_correlation', table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    op.drop_table('settings')
    op.drop_index(op.f('ix_secrets_owner_ext_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_label'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_table('roles')
    op.drop_index(op.f('ix_notifications_ts'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_ext_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_hosts_provider_ext_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_name'), table_name='hosts')
    op.drop_table('hosts')
    op.drop_table('host_groups')
    op.drop_table('extensions')
    op.drop_index(op.f('ix_dashboard_layouts_user_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_connector_instances_ext_id'), table_name='connector_instances')
    op.drop_table('connector_instances')
    op.drop_index('ix_audit_ts_action', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_correlation', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_flap_fingerprint_ts', table_name='action_flap_history')
    op.drop_index(op.f('ix_action_flap_history_fingerprint'), table_name='action_flap_history')
    op.drop_table('action_flap_history')
    # ### end Alembic commands ###
