"""wp1 totp_confirmed_at

Revision ID: 88ae66606d3b
Revises: 5637ec0a6a73
Create Date: 2026-09-14 23:02:05.707410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ae66606d3b'
down_revision: Union[str, Sequence[str], None] = '5637ec0a6a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_confirmed_at')
    # ### end Alembic commands ###
